# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bg1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sys,bgres1
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 701)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1000, 700))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 1000, 700))
        self.label.setStyleSheet("border-image: url(:/images/bg1.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 900, 100))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"Algerian\";\n"
"color: rgb(11, 69, 113);\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 247, 910, 250))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(5, 41, 108);\n"
"font: 63 14pt \"Algerian\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(700, 600, 750, 61))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));\n"
"font: 10pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(200, 20, 100, 31))
        self.pushButton.setStyleSheet("font: 10pt \"Algerian\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 20, 150, 31))
        self.pushButton_2.setStyleSheet("font: 10pt \"Algerian\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 20, 150, 31))
        self.pushButton_3.setStyleSheet("font: 10pt \"Algerian\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(750, 20, 150, 31))
        self.pushButton_4.setStyleSheet("font: 10pt \"Algerian\";")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "HEYYY USER!!"))
        self.label_4.setText(_translate("Form", "Nearing the end of the year?? \n"
"With loads and loads of data not able to \n"
"manage & analyse ?\n"
"We are here to  make you\'re task  easier for you to track \n"
"all you\'re data.\n"
" ;)"))
        self.label_5.setText(_translate("Form", "Any Queries?\n"
"Email:customercare@gmail.com"))
        self.pushButton.setText(_translate("Form", "add info"))
        self.pushButton_2.setText(_translate("Form", "display info"))
        self.pushButton_3.setText(_translate("Form", "update info"))
        self.pushButton_4.setText(_translate("Form", "analysis info"))
if __name__ == "__main__":
    app=QtWidgets.QApplication(sys.argv)
    Form=QtWidgets.QMainWindow()
    uI=Ui_Form()
    uI.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
