# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 700)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 10, 171, 681))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bg = QtWidgets.QLabel(self.frame)
        self.bg.setGeometry(QtCore.QRect(0, 0, 191, 661))
        self.bg.setStyleSheet("background-color: rgb(255, 231, 233);")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.incomebtn = QtWidgets.QPushButton(self.frame)
        self.incomebtn.setGeometry(QtCore.QRect(20, 130, 101, 31))
        self.incomebtn.setStyleSheet("font: 10pt \"Algerian\";")
        self.incomebtn.setObjectName("incomebtn")
        self.prodbtn = QtWidgets.QPushButton(self.frame)
        self.prodbtn.setGeometry(QtCore.QRect(20, 200, 101, 31))
        self.prodbtn.setStyleSheet("font: 10pt \"Algerian\";")
        self.prodbtn.setObjectName("prodbtn")
        self.rawbtn = QtWidgets.QPushButton(self.frame)
        self.rawbtn.setGeometry(QtCore.QRect(20, 260, 151, 31))
        self.rawbtn.setStyleSheet("font: 10pt \"Algerian\";")
        self.rawbtn.setObjectName("rawbtn")
        self.salbtn = QtWidgets.QPushButton(self.frame)
        self.salbtn.setGeometry(QtCore.QRect(20, 330, 100, 31))
        self.salbtn.setStyleSheet("font: 10pt \"Algerian\";")
        self.salbtn.setObjectName("salbtn")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 60, 31))
        self.pushButton.setObjectName("pushButton")
        self.bg1 = QtWidgets.QLabel(Form)
        self.bg1.setGeometry(QtCore.QRect(170, 10, 811, 661))
        self.bg1.setStyleSheet("background-color: rgb(255, 196, 199);")
        self.bg1.setText("")
        self.bg1.setObjectName("bg1")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(230, 130, 731, 511))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.bgtitle = QtWidgets.QLabel(Form)
        self.bgtitle.setGeometry(QtCore.QRect(230, 30, 651, 71))
        self.bgtitle.setStyleSheet("font: 20pt \"Algerian\";")
        self.bgtitle.setObjectName("bgtitle")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.incomebtn.setText(_translate("Form", "INCOME"))
        self.prodbtn.setText(_translate("Form", "PRODUCT"))
        self.rawbtn.setText(_translate("Form", "RAW MATERIALS"))
        self.salbtn.setText(_translate("Form", "SALARY"))
        self.pushButton.setText(_translate("Form", "BACK"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        self.bgtitle.setText(_translate("Form", "YOU\'RE DATA IS DISPLAYED HERE"))
if __name__ == "__main__":
    app=QtWidgets.QApplication(sys.argv)
    Form=QtWidgets.QWidget()
    uI=Ui_Form()
    uI.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())