# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LOGWRK.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(283, 196)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 271, 181))
        self.widget.setStyleSheet("background-image: url(:/images/workma.jpg);\n"
"border--radius:30px")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(90, 20, 91, 21))
        self.label.setStyleSheet("font: 16pt \"Algerian\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.username = QtWidgets.QLineEdit(self.widget)
        self.username.setGeometry(QtCore.QRect(80, 60, 113, 20))
        self.username.setStyleSheet("border-top-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-right-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(85, 255, 255);")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setGeometry(QtCore.QRect(80, 100, 113, 20))
        self.password.setStyleSheet("border-top-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"border-right-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(85, 255, 255);")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(110, 150, 61, 21))
        self.pushButton.setStyleSheet("font: 14pt \"Algerian\";\n"
"background-image: url(:/images/C:/Users/prakr/OneDrive/Pictures/94423778_101077344923072_6297516989128638464_n.jpg);\n"
"background-color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "LOGIN PAGE"))
        self.username.setText(_translate("Dialog", "USERNAME"))
        self.password.setText(_translate("Dialog", "PASSWORD"))
        self.pushButton.setText(_translate("Dialog", "LOGIN"))
import res1_rc
